### ISSUE TITLE
Make the —dist option practically useful

### ISSUE THREAD

**Issue by jaro3** [svanas/nefertiti#56]
In a fast crashing market the bot quickly exhausts funds by placing buy orders too close to each other (esp. with short --repeat).  

It would be great, if the bot can look for another support level within the given —pip limit if the first order candidate is closer than —dist (also from the previously bought and not sold yet order!) and skips the order + errors if it cannot find more distant one...  The --ignore=error option could make the bot to place the order anyway even if it cannot find more distant support level.

**Comment by jaro3** [comment]
Can be also feature request: Prevent fast funds exhaustion in a stormy market by riding it with the bot taking advantage of the --dist option

**Comment by syzygy800** [comment]
I have made a quickhack thinning the order book respecting the "dist" parameter. Example:
`nefertiti.exe buy [..] --market=CHZEUR --top=2 --price=100 --dist=5
Book before thinning:
  [{CHZEUR 0.19 495208.11} {CHZEUR 0.21 329277} {CHZEUR 0.26 249596} {CHZEUR 0.22 149988} {CHZEUR 0.2 81928.23999999999} {CHZEUR 0.23 54496} {CHZEUR 0.24 48352} {CHZEUR 0.25 35944}]
Book after thinning:
  [{CHZEUR 0.26 249596} {CHZEUR 0.24 48352} {CHZEUR 0.22 149988} {CHZEUR 0.2 81928.23999999999} {CHZEUR 0.19 495208.11}]

[{"market":"CHZEUR","price":0.26,"size":385},{"market":"CHZEUR","price":0.24,"size":417}]
`
Without the thinning the output was:
`[WARN] Distance between your CHZEUR orders is 4.00 percent (too low, less than 5 percent)
[{"market":"CHZEUR","price":0.26,"size":192},{"market":"CHZEUR","price":0.25,"size":200}]
`

What I did:
 - sort the orderbook containing all orders (descending)
 - create a new book where each entry has a price distance of at least  "dist" 
 - this book is then rest of NEF's code

This simple approach seems to work, because the dist-stuff is the last thing happening before setting the orders. So the discareded book entries are not needed for other calculations of NEF.

**Comment by jaro3** [comment]
It would be great if the bot can place orders at predefined intervals (like ladder) if it cannot find any supports which fit the --dist parameter.

Then there is the aggregation issue.....

**Comment by jaro3** [comment]
can the bot default to ladder type orders if it cannot find any supports within the --dist and --pip values?
